//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace _18DH110115_LTW.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ProductImage = "~/Content/images/default_img.png";
        }

        // scalar properties
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductImage { get; set; }

        // reference properties
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        // Thêm trường dữ liệu UploadImg kiểu HttpPostedFile để upload file ảnh
        // Dùng thuộc tính [NotMapped] để đánh dấu đây là trường dữ liệu không lưu vào DB
        [NotMapped]
        [Url(ErrorMessage = "Vui lòng nhập URL hợp lệ")]
        [RegularExpression(@"^https?://.+\.(png|jpg|jpeg|gif)(\?.*)?$",
     ErrorMessage = "URL phải kết thúc bằng .png, .jpg, .jpeg, .gif")]
        public string UploadImg { get; set; }
    }
}
